test:
  content: this is spring cloud config from github resource edit 8888
  
server: 
  port:  6002

eureka: 
  client: 
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/

spring: 
  application: 
    name: springconfig
  cloud: 
    bus:
      enabled: true
      trace: 
        enabled: true
  rabbitmq: 
    host: 10.2.8.70
    port: 5672
    username: spring_cloud
    password: P@ssw0rd

management: 
  endpoints: 
    web: 
      exposure: 
        include: refresh
  security:
   enabled: false